Forum
Staskataaa/Stanislav-Stoychev-Internship-Grafixoft pull request #30
Opened 2022-10-19 07:33 UTC by Staskataaa

2022-10-19 11:08 UTC, georgiborisob99 commented on Forum/DDL Forum/Account Table.sql
> +fk_post_id int FOREIGN KEY REFERENCES POST(id) ON DELETE CASCADE)
Remove fk for post table

2022-10-19 11:08 UTC, georgiborisob99 commented on Forum/DDL Forum/Account Table.sql
> +id int IDENTITY(1, 1) NOT NULL PRIMARY KEY,
Use Guid

2022-10-19 11:08 UTC, georgiborisob99 commented on Forum/DDL Forum/Database Creation.sql
> +CREATE DATABASE FORUM
Check if database exist !

2022-10-19 11:08 UTC, georgiborisob99 commented on Forum/DDL Forum/Account_role.sql
> +END
I suggest Role table to be like enum with static data containing roleId, role_description, and role_priority.

2022-10-19 11:08 UTC, georgiborisob99 commented on Forum/DDL Forum/Account_role.sql
> +IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES  WHERE TABLE_NAME = 'ACCOUNT_ROLE')
select 1

2022-10-19 11:08 UTC, georgiborisob99 commented on Forum/DDL Forum/Comment Table DDL.sql
> +IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES  WHERE TABLE_NAME = 'COMMENT')
select 1

2022-10-19 11:08 UTC, georgiborisob99 commented on Forum/DDL Forum/Post Table DDL.sql
> +fk_comment_id int FOREIGN KEY REFERENCES COMMENT(id) ON DELETE CASCADE)
Not needed

2022-10-19 11:08 UTC, georgiborisob99 commented on Forum/DDL Forum/Post Table DDL.sql
> +likes int NOT NULL,
I suggest likes to be a different table, Don't we want to have likes on comments ?

2022-10-19 11:08 UTC, georgiborisob99 commented on Forum/DDL Forum/Topic Table.sql
> +IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES  WHERE TABLE_NAME = 'TOPIC')
You can add more fields to topic table for example description, topic owner exc

2022-10-19 11:08 UTC, georgiborisob99 commented on Forum/DDL Forum/Topic_Post Table.sql
> +IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES  WHERE TABLE_NAME = 'TOPIC_POST')
The whole table is redundant. Post should have column topic_id

2022-10-19 11:08 UTC, georgiborisob99 commented on Forum/DML Forum/Forum DML.sql
> +USE FORUM
Update the DML's after the table changes :)

2022-10-19 11:08 UTC, georgiborisob99 commented on Forum/DML Forum/Forum DML.sql
> +DELETE FROM ACCOUNT WHERE ( ACCOUNT.id = '1');
Remove delete from dml scripts

2022-11-02 09:25 UTC, bvalchev requested changes

2022-11-02 09:25 UTC, bvalchev commented on Forum/DDL Forum/Account Role DDL.sql
> +/*
This comment is not needed. The script name should be descriptive enough

2022-11-02 09:25 UTC, bvalchev commented on Forum/DDL Forum/React Table DDL.sql
> +END
This table structure seems to be wrong. React Id does not make any sense. It will be better if this is the guid of the role. If this is going to be the structure you can attach them to each of the other tables. Lets discuss tomorrow

2022-11-02 09:25 UTC, bvalchev commented on Forum/DDL Forum/Topic Table DDL.sql
> +	topic_owner uniqueIdentifier);
If this is a guid make it clear that it is a guid.

2022-11-02 09:25 UTC, bvalchev commented on Forum/Forum API/Forum API/Controllers/AccountController.cs
> +        [Route("/account/{roleDescription}")]
Why roleDescription?

2022-11-02 09:25 UTC, bvalchev commented on Forum/Forum API/Forum API/Controllers/AccountController.cs
> +        public async Task<HttpResponseMessage> DeleteAccount(Guid guid)
accountGuid will sound better

2022-11-02 09:25 UTC, bvalchev commented on Forum/Forum API/Forum API/Controllers/AccountController.cs
> +        [Route("/account/update")]
you don't need update in the url when the method is PUT

2022-11-02 09:25 UTC, bvalchev commented on Forum/Forum API/Forum API/Controllers/AccountController.cs
> +        [Route("/account/{accountPoints}")]
Can't get the purpose of this endpoint

2022-11-02 09:25 UTC, bvalchev commented on Forum/Forum API/Forum API/Controllers/AccountRoleController.cs
> +        [Route("/accountRole/all")]
no need of all here

2022-11-02 09:25 UTC, bvalchev commented on Forum/Forum API/Forum API/Controllers/AccountRoleController.cs
> +        [Route("/accountRole/remove")]
Same as above

2022-11-02 09:25 UTC, bvalchev commented on Forum/Forum API/Forum API/Controllers/AccountRoleController.cs
> +        [Route("/accountRole/update")]
same as above

2022-11-02 09:25 UTC, bvalchev commented on Forum/Forum API/Forum API/Controllers/AccountRoleController.cs
> +            throw new StackOverflowException("123123");
?

2022-11-02 09:25 UTC, bvalchev commented on Forum/Forum API/Forum API/Controllers/AccountRoleController.cs
> +            throw new StackOverflowException("123123");
Very descriptive exception :D

2022-11-02 09:25 UTC, bvalchev commented on Forum/Forum API/Forum API/Filters/ExceptionFilter.cs
> +            return e switch
Here it is good to catch only custom exception, because the framework knows how to process default exceptions. If you want you can keep the default, but also add custom ones

2022-11-02 09:25 UTC, bvalchev commented on Forum/Forum API/Forum API/Filters/ExceptionFilter.cs
> +    public class ExceptionFilter : IActionFilter
Use ActionFilter class and override the onActionExecuted

2022-11-02 09:25 UTC, bvalchev commented on Forum/Forum API/Forum API/Filters/ExceptionFilter.cs
> +        public void OnActionExecuting(ActionExecutingContext context)
bad practice

2022-11-02 09:25 UTC, bvalchev commented on Forum/Forum API/Forum API/Models/Account.cs
> +        public Guid AccountId { get; } = Guid.NewGuid();
no need to add account before each of those props

2022-11-02 09:25 UTC, bvalchev commented on Forum/Forum API/Forum API/Models/Account.cs
> +        public Guid AccountId { get; } = Guid.NewGuid();
did we tested if this will overwrite the guids in the dbs each time

2022-11-02 09:25 UTC, bvalchev commented on Forum/Forum API/Forum API/Models/AccountRole.cs
> +        public Guid RoleId { get; } = Guid.NewGuid();
Same as for the other model

2022-11-02 09:25 UTC, bvalchev commented on Forum/Forum API/Forum API/Models/AccountRole.cs
> +        public int? RolePriority { get; set; } = null!;
int? and then null! ?

2022-11-02 09:25 UTC, bvalchev commented on Forum/Forum API/Forum API/Models/Account.cs
> +        public Guid AccountRoleId { get; set; }
no need for setters for all Ids

2022-11-02 09:25 UTC, bvalchev commented on Forum/Forum API/Forum API/Models/React.cs
> +        public virtual Guid PostId { get; set; }
again no need for set. Carefully check if you need setters for all of the props in all of the models, because that way you break the encapsulation principle

2022-11-02 09:25 UTC, bvalchev commented on Forum/Forum API/Forum API/Program.cs
> +builder.Services.AddAuthorization();
You can move those dependencies into separate file so it is easier for you to manage them

2022-11-02 09:25 UTC, bvalchev commented on Forum/Forum API/Forum API/Repository/BaseRepository.cs
> +        public ForumContext Repository_Context { get; set; }
Use proper casing

2022-11-02 09:28 UTC, Staskataaa commented on Forum/DDL Forum/Comment Table DDL.sql
> +	comment_react_id uniqueIdentifier NOT NULL UNIQUE);
Add user id column

2022-11-15 14:12 UTC, closed without merging